"""empty message

Revision ID: 0cd6301b33a0
Revises: f94984dba07b
Create Date: 2021-10-28 17:52:25.675000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd6301b33a0'
down_revision = 'f94984dba07b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'contact', ['full_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact', type_='unique')
    # ### end Alembic commands ###
